services:
  manga_image_translator:
    build:
      context: ./../../
    container_name: manga_image_translator_localdev
    # Batch Mode
    #command: local --verbose --config-file --image "/app/Manga" --use-gpu  
    # Web Mode 
    entrypoint: ["python", "server/main.py"]
    command: ["--start-instance", "--host=0.0.0.0", "--port=5003", "--use-gpu"]

    volumes:
      - ./../../manga_image_translator_localdev:/app
      
    ports:
      - 5003:5003

    ipc: host

    environment:
      # GPU Configuration
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      
      # API Keys (configure as needed)
      OPENAI_API_KEY: ''
      OPENAI_API_BASE: ''
      OPENAI_MODEL: ''
      
      # Other translator APIs
      BAIDU_APP_ID: ''
      BAIDU_SECRET_KEY: ''
      YOUDAO_APP_KEY: ''
      YOUDAO_SECRET_KEY: ''
      DEEPL_AUTH_KEY: ''
      GROQ_API_KEY: ''
      GEMINI_API_KEY: ''
      DEEPSEEK_API_KEY: ''

    # For GPU
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
