services:
  manga_image_translator:
    image: zyddnys/manga-image-translator:main
    container_name: manga_image_translator_gpu
    entrypoint: python
    command: server/main.py --verbose --start-instance --host=0.0.0.0 --port=5003 --use-gpu
    volumes:
            # Mount config folder - QUAN TRỌNG để load config file
      - ./../../config:/app/config
      # Mount result folder để lưu output
      - ./../../result:/app/result
      - ./../../server/main.py:/app/server/main.py
      - ./../../server/instance.py:/app/server/instance.py
      - ./../../server/request_extraction.py:/app/server/request_extraction.py
      - ./../../server/myqueue.py:/app/server/myqueue.py
      - ./../../server/to_json.py:/app/server/to_json.py
      - ./../../server/streaming.py:/app/server/streaming.py
      - ./../../server/sent_data_internal.py:/app/server/sent_data_internal.py
    ports:
      - 5003:5003
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu] 
    environment:  
      # baidu  
      BAIDU_APP_ID: ''  
      BAIDU_SECRET_KEY: ''  
      
      # youdao  
      YOUDAO_APP_KEY: ''  
      YOUDAO_SECRET_KEY: ''  
      
      # deepl  
      DEEPL_AUTH_KEY: ''  
      
      # openai/ChatGPT  
      OPENAI_API_KEY: ''
      OPENAI_API_BASE: ''
      OPENAI_MODEL: ''
      OPENAI_HTTP_PROXY: ''
      
      # glossary
      OPENAI_GLOSSARY_PATH: './dict/mit_glossary.txt'
      
      # Groq  
      GROQ_API_KEY: ''  
      GROQ_MODEL: 'mixtral-8x7b-32768'  
      
      # sakura  
      SAKURA_API_BASE: 'http://127.0.0.1:8080/v1'  
      SAKURA_VERSION: '0.9'  
      SAKURA_DICT_PATH: './sakura_dict.txt'  
      
      # Caiyun  
      CAIYUN_TOKEN: ''  
      
      # Gemini  
      GEMINI_API_KEY: 'AIzaSyA8bp0L7p21ExKdRua3G43oPLLvBrlAorg'  
      GEMINI_MODEL: 'gemini-2.5-flash'  
      
      # DeepSeek  
      DEEPSEEK_API_KEY: ''  
      DEEPSEEK_API_BASE: 'https://api.deepseek.com'  
      DEEPSEEK_MODEL: 'deepseek-chat'  
      
      # Custom OpenAI compatible API  
      CUSTOM_OPENAI_API_KEY: 'ollama'  
      CUSTOM_OPENAI_API_BASE: 'http://localhost:11434/v1'  
      CUSTOM_OPENAI_MODEL: ''  
      CUSTOM_OPENAI_MODEL_CONF: ''        
